service: serverless-nest-pg

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}
    NODE_ENV: ${env:NODE_ENV}

functions:
  api:
    handler: dist/main.handler
    events:
        - http:
            path: /users
            method: ANY

        - http:
            path: /auth/register
            method: POST

        - http:
            path: /auth/signin
            method: POST

        - http:
            path: /auth/profile
            method: GET

        - http:
            path: /wallet/get
            method: GET

        - http:
            path: /wallet/add
            method: POST

        - http:
            path: /budgets/get
            method: GET

        - http:
            path: /budgets/add
            method: POST

        - http:
            path: /transaction/add
            method: POST

        

plugins:
  - serverless-offline
