name: Laravel CI CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - name: Install Dependencies
        run: |
          cd server 
          sudo apt-get install unzip
          composer install --prefer-dist --no-interaction

      - name: Setup Env
        run: |
          cd server 
          cp .env.example .env

      - name: Generate application key
        run: |
          cd server 
          php artisan key:generate

      - name: Run tests and generate report
        run: |
          cd server 
          php artisan migrate --env=testing
          php artisan test --log-junit=tests/_output/test-report.xml

      

